// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfHzPkUao8o07B6yIyPggGyVtbQX3KaAk',
    appId: '1:467530899143:web:fb2bf3d744de475f5628e2',
    messagingSenderId: '467530899143',
    projectId: 'esercizio-guidato',
    authDomain: 'esercizio-guidato.firebaseapp.com',
    storageBucket: 'esercizio-guidato.firebasestorage.app',
    measurementId: 'G-ZR4ZG8KKRQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACT-wogAap5wGdRjhnnhk7uSS2x8nYvq4',
    appId: '1:467530899143:android:d66f6087afad4e1d5628e2',
    messagingSenderId: '467530899143',
    projectId: 'esercizio-guidato',
    storageBucket: 'esercizio-guidato.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkjbDwqjhHdiU4UAtarb9Unx_orpWO88k',
    appId: '1:467530899143:ios:d065e08619200fec5628e2',
    messagingSenderId: '467530899143',
    projectId: 'esercizio-guidato',
    storageBucket: 'esercizio-guidato.firebasestorage.app',
    iosBundleId: 'com.example.esercizioGuidato',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkjbDwqjhHdiU4UAtarb9Unx_orpWO88k',
    appId: '1:467530899143:ios:d065e08619200fec5628e2',
    messagingSenderId: '467530899143',
    projectId: 'esercizio-guidato',
    storageBucket: 'esercizio-guidato.firebasestorage.app',
    iosBundleId: 'com.example.esercizioGuidato',
  );
}
